version: '3.8'

services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: zmusic
    ports:
      - "3000:3000" 
    restart: unless-stopped
    networks:
      - react-network

networks:
  react-network:
    driver: bridge
