# zmusic/docker-compose.yml
version: '3.8'

services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: zmusic
    restart: unless-stopped
    networks:
      - react-network

  nginx:
    image: nginx:latest
    container_name: zmusic-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - react-app
    restart: unless-stopped
    networks:
      - react-network

networks:
  react-network:
    driver: bridge